from resolving import FunctionHandle as FunctionHandle
from resolving.type_without_holes import Type as Type, CustomTypeType as CustomTypeType, FunctionType as FunctionType, PtrType as PtrType, NamedType as NamedType
from unstacking import Break as Break
from inference.inference import (
        infer_function as infer_function,
        InferenceException as InferenceException,
)
__all__ = ['Number', 'String']
from inference.words import (
        Word as Word,
        NumberWord as Number,
        StringWord as String,
        Call as Call,
        Scope as Scope,
        IndirectCall as IndirectCall,
        InitLocal as InitLocal,
        SetLocal as SetLocal,
        GetLocal as GetLocal,
        RefLocal as RefLocal,
        StoreLocal as StoreLocal,
        Add as Add,
        Sub as Sub,
        Mul as Mul,
        Mod as Mod,
        Div as Div,
        Eq as Eq,
        NotEq as NotEq,
        Ge as Ge,
        Gt as Gt,
        Le as Le,
        Lt as Lt,
        And as And,
        Or as Or,
        Not as Not,
        Drop as Drop,
        Flip as Flip,
        Shl as Shl,
        Shr as Shr,
        Rotl as Rotl,
        Rotr as Rotr,
        Store as Store,
        MemCopy as MemCopy,
        MemFill as MemFill,
        MemGrow as MemGrow,
        SetStackSize as SetStackSize,
        Uninit as Uninit,
        Load as Load,
        Cast as Cast,
        If as If,
        Loop as Loop,
        Block as Block,
        FunRef as FunRef,
        Sizeof as Sizeof,
        GetField as GetField,
        MakeStruct as MakeStruct,
        MakeStructNamed as MakeStructNamed,
        FieldInit as FieldInit,
        MakeVariant as MakeVariant,
        MatchVoid as MatchVoid,
        Match as Match,
        MatchCase as MatchCase,
        FieldAccess as FieldAccess,
)
from inference.top_items import (
        Function as Function,
        Local as Local,
        Extern as Extern,
        Global as Global,
)
from inference.module import (
        Module as Module,
)
