from __future__ import annotations

__all__ = ['MatchVoid']

from resolving import ROOT_SCOPE as ROOT_SCOPE, ScopeId as ScopeId
from resolving.words import MatchVoidWord as MatchVoid
from unstacking import (
        MemCopy as MemCopy,
        MemFill as MemFill,
        MemGrow as MemGrow,
        SetStackSize as SetStackSize,
)

from monomorphization.monomizer import (
        I32_ID as I32_ID,
        Add as Add,
        And as And,
        Block as Block,
        Break as Break,
        Call as Call,
        Cast as Cast,
        Div as Div,
        Drop as Drop,
        Eq as Eq,
        Extern as Extern,
        FieldAccess as FieldAccess,
        FieldInit as FieldInit,
        Flip as Flip,
        Function as Function,
        FunRef as FunRef,
        Ge as Ge,
        GetField as GetField,
        GetLocal as GetLocal,
        GlobalId as GlobalId,
        Gt as Gt,
        If as If,
        IndirectCall as IndirectCall,
        InitLocal as InitLocal,
        Le as Le,
        Load as Load,
        Local as Local,
        LocalId as LocalId,
        Loop as Loop,
        Lt as Lt,
        MakeStruct as MakeStruct,
        MakeStructNamed as MakeStructNamed,
        MakeVariant as MakeVariant,
        Match as Match,
        Mod as Mod,
        Monomized as Monomized,
        Mul as Mul,
        Not as Not,
        NotEq as NotEq,
        Number as Number,
        Or as Or,
        RefLocal as RefLocal,
        Rotl as Rotl,
        Rotr as Rotr,
        Scope as Scope,
        SetLocal as SetLocal,
        Shl as Shl,
        Shr as Shr,
        Signature as Signature,
        Sizeof as Sizeof,
        Store as Store,
        StoreLocal as StoreLocal,
        String as String,
        Struct as Struct,
        Sub as Sub,
        TypeDefinition as TypeDefinition,
        Uninit as Uninit,
        Variant as Variant,
        Word as Word,
        can_live_in_reg as can_live_in_reg,
        field_offset as field_offset,
        global_lives_in_memory as global_lives_in_memory,
        local_lives_in_memory as local_lives_in_memory,
        monomize as monomize,
        type_size as type_size,
)
from monomorphization.type import (
        I8 as I8,
        I32 as I32,
        I64 as I64,
        Bool as Bool,
        CustomTypeHandle as CustomTypeHandle,
        CustomTypeType as CustomTypeType,
        FunType as FunType,
        PtrType as PtrType,
        Type as Type,
        TypeId as TypeId,
)
